server:
  port: 80
  
  
eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://james1.com:7001/eureka/,http://james2.com:7002/eureka/,http://james3.com:7003/eureka/